# Generated by Django 4.0.5 on 2022-07-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pais',
            field=models.CharField(max_length=150),
        ),
    ]
